name: CI

env:
  SONAR_SCANNER_VERSION: 5.0.1.3006

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "src/test/java/**"
      - "target/**"

  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "src/test/java/**"
      - "target/**"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache files
        uses: actions/cache@v4
        with:
          path: ~/.sonar
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # -----------------------------
      # CodeScan Analysis - Push
      # -----------------------------
      - name: Run CodeScan On Push
        if: github.event_name == 'push'
        uses: codescan-io/codescan-scanner-action@2.0
        with:
          scanChangedFilesOnly: true
          organization: prof
          projectKey: profiles-40
          codeScanUrl: https://test.codescan.io/
          login: squ_91f6d32fee1b241fdadc3057ab60820b4f33904c

          # SARIF generation disabled
          # generateSarifFile: true

      # -----------------------------
      # CodeScan Analysis - Pull Request
      # -----------------------------
      - name: Run CodeScan On PR
        if: github.event_name == 'pull_request'
        uses: codescan-io/codescan-scanner-action@2.0
        with:
          scanChangedFilesOnly: true
          organization: prof
          projectKey: profiles-40
          codeScanUrl: https://test.codescan.io/
          login: squ_91f6d32fee1b241fdadc3057ab60820b4f33904c

          # SARIF generation disabled
          # generateSarifFile: true

          args: |
            sonar.pullrequest.branch=${{ github.head_ref }}
            sonar.pullrequest.base=${{ github.base_ref }}
            sonar.pullrequest.key=${{ github.event.number }}

      # -----------------------------
      # SARIF Upload - Disabled
      # -----------------------------
      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v4
      #   with:
      #     sarif_file: codescan.sarif

      # -----------------------------
      # SARIF Artifact Upload - Disabled
      # -----------------------------
      # - name: Archive CodeScan SARIF results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: codescan.sarif
      #     path: codescan.sarif
